version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sshmanager
    main: ./cmd/sshmanager
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, 386]
    goarm: [6, 7]
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: sshmanager
    ids: [sshmanager]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

homebrew_casks:
  - name: sshmanager
    ids: [sshmanager]
    binaries: [sshmanager]
    description: Simple SSH manager CLI tool.
    homepage: https://github.com/emirhangumus/sshmanager
    license: Apache-2.0
    repository:
      owner: emirhangumus
      name: homebrew-tap

nfpms:
  - id: sshmanager
    maintainer: Emirhan Gümüş <[email protected]>
    bindir: /usr/bin

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:"]

release:
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
